#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#ITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

import sys
from argparse import ArgumentParser

import csv

def parse_arguments():
    """ Process command line arguments """
    parser = ArgumentParser(description='Grabs tables from html')
    parser.add_argument('-u', '--url', required=True, help='absolute path to jb.txt file')
    args = parser.parse_args()
    return args


def extract_judges(reader):
    """ Get data from rows """
    judges_list = []
    try:
        for row in reader:
            if reader.line_num != 1:
                judge = [row[2], row[3], row[1]]
                judges_list.append(' '.join(judge))
    except csv.Error as e:
        sys.exit('file %s, line %d: %s' % (reader, reader.line_num, e))
    
    return judges_list




def main():
    '''
    Purpose::
        scrape_federal_judges.py reads in and processes the file downloaded from
        http://www.uscourts.gov/JudgesAndJudgeships/BiographicalDirectoryOfJudges.aspx
        which is also saved locally for convenience.
        The file contains and export of all data in the Biographical Directory of Federal Judges, 
        1789-present.
        The database export is in the form of a comma-delimited text file that can be imported 
        into a spreadsheet program. The data is updated nightly at midnight at the link above.
        
        A few notes on using the database:
            The Judge Identification Number is an arbitrary number generated by the Federal 
            Judicial History Office to organize the database and does not represent the order 
            in which judges were appointed to the bench. When a judge is appointed to a 
            subsequent court, that entry is also preceded by the original Judge Identification Number.
            
            The large number of blank fields in most records is to accommodate those judges who 
            have been appointed to multiple judicial positions in the federal courts. This 
            makes the data easier to drop into a spreadsheet program.
            
            Retirement from Active Service refers to the date a judge assumes senior status. 
            When a judge fully retires, resigns, dies, is elevated to another court, or is 
            removed from office, that date is listed under Termination Date followed 
            by the reason for termination.
            
            Published references to information from this database should use the 
            citation: History of the Federal Judiciary. http://www.fjc.gov. Web 
            site of the Federal Judicial Center, Washington, DC.
            
            If you have any questions about the information in the database, please 
            contact the Federal Judicial History Office at uhistory@fjc.gov or 202-502-4180.
    Input::
    
    Output::
    
    Assumptions::
    '''
    # Get arguments
    args = parse_arguments()
    if args.url:
        url = args.url

    # Get file and read it into structure
    try:
        with open(url, 'rb') as csvfile:
            reader = csv.reader(csvfile)
            judges = extract_judges(reader)
                
    except IOError as e:
        print 'An error occured fetching %s \n %s' % (url, e.reason)   
        return 1

    f = open('US_federal_judges.txt', 'w')
    # Print data
    #f.write("\n".join(str(i).encode('utf8') for i in judges))
    for i in judges:
        f.write((i).encode('utf8') +'\n')

    f.close()


if __name__ == '__main__':
    status = main()
    sys.exit(status)

